### ISSUE TITLE
A usage question CAN Sniffer?

### ISSUE THREAD

**Issue by mgiaco** [mguentner/cannelloni#18]
Dose anyone a solution to sniff can data via wire-shark on windows. I taught it could be possible to use a raspberry pi with and and cannelloni to build a CAN to Ethernet Bridge. Is it possible to use the Bridged Data in wire-shark to analyse CAN Data?

Many thanks
cheers
mathias

**Comment by mguentner** [comment]
Yes. Either you open a wireshark capture file that you have recorded on the RPi from the SocketCAN interface or you write a dissector for the cannelloni protocol.

It's really easy!

https://wiki.wireshark.org/Lua/Dissectors

Please share the code if it works for you.
