### ISSUE TITLE
Define struct canfd_frame on platforms with old kernel versions

### ISSUE THREAD

**Issue by mguentner** [mguentner/cannelloni#2]
Check for

```
if LINUX_VERSION_CODE < KERNEL_VERSION(3,6,0)
```

and define `struct canfd_frame` like torvalds/linux@7c9416365c60f150ef8961a2855fafbc7394ad6b does.

**Comment by hartkopp** [comment]
Where would you suggest to check the KERNEL_VERSION?

The can-utils come with their own include files to make sure the can-utils compile even in older environments - similar to the iproute2 package. The tools inside can-utils check at runtime whether the Linux kernel understands the new options & data structures.

**Comment by mguentner** [comment]
The `FrameBuffer` currently stores the frames in the 'native' `canfd_frame` struct. Therefore I suggest to place a check like
```
#include <linux/version.h>
#if KERNEL_VERSION_CODE < KERNEL_VERSION(3,6,0)
struct canfd_frame {
	canid_t can_id;  /* 32 bit CAN_ID + EFF/RTR/ERR flags */
	__u8    len;     /* frame payload length in byte */
	__u8    flags;   /* additional flags for CAN FD */
	__u8    __res0;  /* reserved / padding */
	__u8    __res1;  /* reserved / padding */
	__u8    data[CANFD_MAX_DLEN] __attribute__((aligned(8)));
};
#endif
```
into `can.h` [1]. Of course, only `struct canfd_frame` is not enough since `CANFD_MTU` etc. needs
to be defined aswell.

The alternative and better approach is to put a current `can.h` from the kernel into the source of cannelloni and include it if the KERNEL_VERSION_CODE is too old like this:

```
#include <linux/version.h>
#if KERNEL_VERSION_CODE < KERNEL_VERSION(3,6,0)
#include "linux/can.h"
#else
#include <linux/can.h>
#endif
```
and rename `can.h` to `cannelloni.h`.
So this would be a mix of both with the advantage that when compiled on recent kernels, the header of the kernel will be used instead of a potentially older version.

[1] https://github.com/mguentner/cannelloni/blob/master/can.h

**Comment by hartkopp** [comment]
What about
#ifndef CANFD_MTU
(all the needed stuff)
#endif 

somewhere in your include files?

**Comment by mguentner** [comment]
@hartkopp, I have tested this in a Debian Wheezy Vagrant box with Kernel version 3.2.0-4.
CMake/Make prepends the CAN headers as expected. On my machine (3.19.2), the headers in `/usr/include/linux` are used. :thumbsup:

**Comment by yegorich** [comment]
@mguentner could you please make a new release tag, so that this commit is included? We experience build breakage in Buildroot with older toolchains. Thanks.

**Comment by mguentner** [comment]
Will do!
