### ISSUE TITLE
how to replay the pcap file to a can interface

### ISSUE THREAD

**Issue by johnchan20** [mguentner/cannelloni#26]
when i use tcpdump to capture the  data by cangen to a pcap file,this process is work fine .But how to replay the pcap file to a can interface?
i use wireshark to play the pcap file and find that the protol is llc not udp,udpreplay doesn't support,
please help me!

**Comment by mguentner** [comment]
use candump instead of tcpdump:

https://sgframework.readthedocs.io/en/latest/cantutorial.html

**Comment by johnchan20** [comment]
candump is ok ,but i want to write to a pcap file and replay to a can interface.

**Comment by mguentner** [comment]
Please read the tutorial. Use canplayer.

**Comment by johnchan20** [comment]
i know ,canplayer just support the can log file to replay,but not support to replay my pcap file.

**Comment by mguentner** [comment]
I don't know that.
