### ISSUE TITLE
Add support for CAN Filters

### ISSUE THREAD

**Issue by CanBusHack** [mguentner/cannelloni#32]
Sending all data may not be required.  In the case of Diagnostics, etc.

Suggest adding CAN Filters:

`setsockopt(s, SOL_CAN_RAW, CAN_RAW_JOIN_FILTERS, &rfilter, sizeof(rfilter));`

so that only filtered data is transmitted from server to client.

**Comment by mickeyl** [comment]
That would be a great additional feature. I'm using `cannelloni` here for developing ECU reprogramming software and in normal mode, ECUs talk to a huge number of other ECUs, all of which are not interesting for the communication between tester/updater and ECU.

**Comment by mguentner** [comment]
I am not sure whether filtering should be a feature of cannelloni.
The primary objective of the tool is to provide a simple and effective means of bridging two CAN bus interfaces. Filtering and/or manipulation seems a bit out-of-scope at the moment.
I have documented an approach using `cangw` and a virtual CAN bus here in the README: https://github.com/mguentner/cannelloni#filtering

Let me know whether this works for you. Maybe you have case that justifies adding this feature to cannelloni itself.
