### ISSUE TITLE
Question on timestamps

### ISSUE THREAD

**Issue by adeboeve** [mguentner/cannelloni#34]
Is it possible to preserve the timestamps from the host CAN interface when accessing the CAN data from the client?

**Comment by adeboeve** [comment]
Thanks for the reply. I am running cannelloni on a raspberry pi with pcan chip's and it works very well over UDP. It appears to keep up perfectly fine with multiple CAN FD channels. Thanks for sharing this!

Any thoughts on what it would take to include the timestamps from the host in the protocol? These could be accessed alternatively by calling `candump` with the `-H` option on the client PC. 

This would enable a host PC to effectively work as a CAN logger, that is easily accessed from a client PC with socketcan tools.

**Comment by mguentner** [comment]
I don't believe it's possible to fake / spoof timestamps using SocketCAN. Even if you would use the `-H` option on a `vcan` device, you would system time again as the hardware is virtualized by the kernel, hence the time will be the system time.

If you need an (additional) remote CAN logger, I suggest to use `netcat` on the `client PC` and pipe the output of `candump` on the host PC to it using another instance of `netcat`. If you need a secure connection, use ssh instead.

This should work (untested):

` client $ nc -l 1337`

` host $ candump can0 | nc $IP_OF_CLIENT 1337`

**Comment by hartkopp** [comment]
You would need `candump -L can0` to generate the logfile format on stdout.

`client $ nc -l 1337 | canplayer vcan0=can0`
`host $ candump -L can0 | nc $IF_OF_CLIENT 1337`

Btw. you might also give ssh the candump command and pipe the output into canplayer or a logfile.
