### ISSUE TITLE
Memory corruption in TCPThread leads to corrupt CannelloniDataPacket

### ISSUE THREAD

**Issue by RandomTangent99** [mguentner/cannelloni#40]
Hello,

I was running the following command: 

`cannelloni -C c -R <IPADDRESS> -I vcan0 -r <PORT>`

I received the following blurb of error messages:

`
cannelloni -C c -R <IPADDRESS> -I vcan0 -r <PORT>
INFO:tcpthread.cpp[172]:run:Connecting to <IPADDRESS:PORT>...
INFO:canthread.cpp[108]:run:CANThread up and running
INFO:tcpthread.cpp[180]:run:Connected!
ERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received incomplete packetERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet / can header corrupt!ERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet
ERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet
ERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet / can header corrupt!ERROR:udpthread.cpp[139]:parsePacket:Received wrong versionERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet / can header corrupt!ERROR:udpthread.cpp[139]:parsePacket:Received wrong version
`
So I went into udpthread.cpp and the parsePacket function and added some extra debug messages to show what the value of the lengths and such that are out of sync. I got the following:

`
cannelloni -C c -R <IPADDRESS> -I vcan0 -r <PORT>
INFO:tcpthread.cpp[172]:run:Connecting to <IPADDRESS:PORT>...
INFO:canthread.cpp[108]:run:CANThread up and running
INFO:tcpthread.cpp[180]:run:Connected!
ERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet / can header corrupt! incomplete packet is 1343 and len is 1346
ERROR:udpthread.cpp[139]:parsePacket:Received wrong version...version is 64
cERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet...incomplete packet is 1351 and len is 1346
ERROR:udpthread.cpp[139]:parsePacket:Received wrong version...version is 0
ERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet / can header corrupt! incomplete packet is 1341 and len is 1346
ERROR:udpthread.cpp[139]:parsePacket:Received wrong version...version is 0
ERROR:udpthread.cpp[139]:parsePacket:Received incomplete packet / can header corrupt! incomplete packet is 1342 and len is 1346
ERROR:udpthread.cpp[139]:parsePacket:Received wrong version...version is 0
`

I know the value for CANNELLONI_FRAME_VERSION is supposed to be 2, so its strange that its changed every time; which seems strange to me.

Let me know if this is fixable, thanks

**Comment by mguentner** [comment]
Please read the review of #38 - TCP is not supported yet.
