### ISSUE TITLE
Support name resolution

### ISSUE THREAD

**Issue by gsalinas** [mguentner/cannelloni#44]
Thanks for the excellent tool! It'd be great if we could provide a hostname and/or FQDN instead of the IP address to connect with machines of a known name but with no consistent IP address. (Currently, using a name seems to fail silently - I suspect when `inet_pton` is called but I haven't tested that or anything.)

**Comment by mguentner** [comment]
Thanks for the feedback. This is indeed an issue, I will fix it asap.
Same for the DNS resolution :)

Would an initial resolution suffice, i.e. hostnames are resolved at startup but IP addresses would not change during runtime of cannelloni?

**Comment by gsalinas** [comment]
Thank you so much! Certainly for me an initial resolution will suffice.

**Comment by mguentner** [comment]
Ping @gsalinas :)

**Comment by gsalinas** [comment]
Thank you so much!
